mdqmmmambin = ""\
"300K constant temp QMMMMD\n"\
" &cntrl\n"\
"  imin=0,\n"\
"  iwrap=1,\n"\
"  irest=0,\n"\
"  ntx=5,\n"\
"  ntb=1,\n"\
"  ntp=0,\n"\
"  ig=-1,\n"\
"  taup=2.0,\n"\
"  cut=16.0,\n"\
"  ntr=0,\n"\
"  tempi=300.0,\n"\
"  temp0=300.0,\n"\
"  ntt=3,\n"\
"  gamma_ln=2.0,\n"\
"  nstlim=0,\n"\
"  dt=0.0005,\n"\
"  ntpr=1,\n"\
"  ntwx=0,\n"\
"  ntwv=-1,\n"\
"  ifqnt=1,\n"\
" /\n"\
" &qmmm\n"\
"  verbosity=1,\n"\
"  qmmask=':1',\n"\
"  nae=1\n"\
" /\n"\
